---
title: "week5_6th script_Rpackage"
output: github_document
date: "2022-08-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 패키지 만들기 

## (1). 사전 준비

일반적으로 R에서 많이 사용하는 패키지를 사용자가 만들 수 있다.

패키지를 만드려면 아래와 같은 외부 패키지를 설치해야 한다.

**install.packages(c("devtools","roxygen2","testthat","knitr"))**을 통해서 패키지를 설치.



## (2). 패키지의 종류

- 소스 패키지 : 개인이 쉽게 파일을 관리하려고 개인적으로 만드는 패키지를 의미.
- 번들 패키지 : 압축 파일 같은 거. install.packages() 해서 쓰는 거. R 공식 홈페이지에 등록하려면 이걸로 해야함.
- 바이너리 패키지 : 그 외의 목적으로 만드는 패키지. 잘 사용하지는 않음.



## (3). 패키지를 위한 Rstudio 열기

File > New project > New directory > R Package using devtools 에서 파일 이름(이때 파일 이름이 패키지 이름임)을 정하고 project를 만듦.

DESCRIPTION과 NAMESPACE, R(폴더) 파일이 뜸

- description : 사용자가 만든 패키지에 대한 설명
- namespace : export할 함수들 및 import한 함수들의 이름들
- R(폴더) : 사용자가 만든 함수들이 r파일로 존재


** Build > configure build tools > generate documentation with Roxygen(Configure) > NAMESPACE file을 체크, install and restart 체크**




## (4). 패키지 만들기 및 부가 설명

- 이제 R script를 새로 만들어서 함수를 만들면 됨.

- 보통 함수는 export할 함수당 r 파일 하나씩 만드는게 국룰.

- export하고 싶은 함수 위(앞)에는 **#' @export** 를 써줘야 함.

- 위와 같은 라벨링을 Roxygen 문법이라고 함.

- 만약 export 안하고 패키지 안에서만 존재하는, 사용자는 건들일 수 없는 function을 만들고 싶다면 만들고 앞에 **#' @export** 안 써주면 됨.

- 패키지 내에서 숨겨진 함수를 사용하는 것은 가능. (다른 파일이더라도)

- 소스 패키지 내에서 외부 R 패키지를 사용해야 할 때 **@importFrom dplyr select** 를 이용하여 dplyr 패키지의 select 함수를 가져와서 쓸 수 있다. 그러면 NAMESPACE에 **importFrom(dplyr,select)**라고 나옴!!




## (5). Roxygen 문법

- #' first example code : 제목
- #' @param x A number : 사용자가 임의로 만든 function의 args들을 설명하는 역할
- #' @param y A number
- #' @return return string hello : ?help했을 때 value에 나오는 부분.
- #' @examples : ?help했을 때 examples에 나오는 부분.
- #' hello(1,1)
- #' hello(2,2)
- #' @export : export하고 싶은 함수에다가 붙여 줌.
- #' @importFrom dplyr select : dplyr에서 select라는 함수를 가져오겠다.
- #' @import dplyr : dplyr을 해당 패키지를 다운받기 전에 미리 다운 받겠다.





- 자세한 사항은 아래 링크 참조 : https://r-pkgs.org/

## (6). Package 완성 후

- 패키지를 모두 완성 한 후에는 
- document()를 사용하여 
- 해당 패키지의 documentation을 업데이트하고 로딩하고 나면 이제 스크립트에서 내가 만든 패키지 install 후 사용할 수 있게 됨.


- 만약에 document()로 해결이 안되면 
- setwd("./패키지이름")  # 내 경우는 setwd("./Graduation")
- document()


- install 코드는 다음과 같음
- setwd(...) # 여기에는 project의 wd를 쓰면 됨. 
- install("패키지 이름") # 이때 패키지 이름은 내가 만든 폴더의 이름!


- 나는 Graduation이라는 proj를 만들었고 위치는 now>graduation paper>algoritm 에 위치해 있었음.
- setwd("C:\\Users\\USER\\Desktop\\now\\grduation paper\\algorithm")
- install("Graduation")
- library(Graduation)

## (7). package 수정 후, update가 안 될 때

- package 만든 R 프로젝트 파일로 들어가서 수정한 스크립트에서 Build > Install package 클릭
- R studio 끄고 다시 틀어서 돌려보기
- Tools > Project Options > Build Tools > Generate documentation with Roxygen 체크
- 위 경로 그대로 들어가서 configure 클릭
- 그 후, NAMESPACE file 체크 & Install and Restart 체크
